version: 0.0
os: linux
files:
  - source: target/springboot-backend-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/deployment/springBoot/  
  - source: application.properties
    destination: /home/ec2-user/deployment/springBoot/
  - source: application_start.sh
    destination: /home/ec2-user/deployment/springBoot/
  - source: application_stop.sh
    destination: /home/ec2-user/deployment/springBoot/
    
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      runas: root
